### ISSUE TITLE
数据库文件能发我一份吗

### ISSUE THREAD

**Issue by 2xiaodi** [boketto-me/cyclop#2]
您好，请问数据库能发我一份吗sea__king@163.com

**Comment by boketto-me** [comment]
@2xiaodi 目前只有admin管理后台有数据库SQL。已经包含在代码仓库里了，路径是：

shield-guard/shield_iadmin/src/main/resources/static/

**Comment by 2xiaodi** [comment]
@boketto-me 感谢您的回复，请问这是系统的全部功能了吗，还是我搭建错误，主要是想找到一个Java开发的入侵检测系统

             
![image](https://user-images.githubusercontent.com/57615079/164179811-1d061667-43ea-48b9-b84f-9d51213c55ad.png)

**Comment by boketto-me** [comment]
@2xiaodi 目前还没做任何业务有关的功能。刚刚完成网络通讯、作业下发，这些基础能力，距离实际可用还是有很长的路要走。驭龙HIDS、AgentSmith等其它开源项目功能更强大，建议关注一下他们。

**Comment by 2xiaodi** [comment]
@boketto-me 好的 感谢您的回复

**Comment by boketto-me** [comment]
@2xiaodi 感谢关注。
